### ISSUE TITLE
Options object pattern for Methods with a lot of Parameters

### ISSUE THREAD

**Issue by philipsens** [frankframework/frontend-conventions#9]
Explanation (JS): https://www.codereadability.com/what-are-javascript-options-objects/
Article (TS): https://medium.com/@bchadwickfrance/the-options-object-pattern-with-typescript-a14f33306ec8

**Comment by mhdirkse** [comment]
Goed idee!

**Comment by Matthbo** [comment]
At what point / amount of parameters would you say its better to switch to an object parameter?
I'm thinking of starting it at 3 or 4, I'm pretty sure most functions use about 1-2 parameters unless a function is very state dependent.

**Comment by philipsens** [comment]
```ts
method(options: {option1: string }): void {
// example
}

method(options: methodOptions): void {
// example
}
```

**Comment by philipsens** [comment]
This should be done with 3 or more parameters

**Comment by philipsens** [comment]
This means that you could also have options as second parameter. When transforming an object it could be nice to have:
```ts
transform(object, {option: true})
```

**Comment by philipsens** [comment]
Add mac param rule to eslint config
